apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-deployment-q6
  # labels:
  #   app: final-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      # app: final-pod
      tag: final-pod
  template:
    metadata:
      labels:
        # app: final-pod
        tag: final-pod
    spec:
      containers:
      - name: final-container
        image: final:v1
        # ports:
        # - containerPort: 80
