apiVersion: v1
kind: Service
metadata:
  name: final-np-service
spec:
  type: NodePort
  selector:
    # app: final-pod
    tag: final-pod
  ports:
    # - protocol: TCP
    - name: final-np  
      port: 8080
      targetPort: 80
      
  